baseUrl: http://localhost:${wiremock.server.port}
server:
  tomcat:
    threads:
      max: 1
      
spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      connection-timeout: 250
  sql:
    init:
      mode: always